//create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": " alex",
    "email": "alex@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}
###
//get ALL users
GET http://localhost:5000/users
###
//get single user
GET http://localhost:5000/users/dc0a13f3-8040-4c0d-acbb-6e9c59156c0e

###
//update user
PATCH  http://localhost:5000/users/dc0a13f3-8040-4c0d-acbb-6e9c59156c0e
Content-Type: application/json

{
    "name": "Ray updated",
    "email": "Ray@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}
###
// delete user 
DELETE http://localhost:5000/users/fce886b0-4a4b-4837-b016-dd77373bd028

###
// login user
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "indah@gmail.com",
    "password": "123456"
}
###
// login admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "ray@gmail.com",
    "password": "123456"
}
###
//end pont me
GET http://localhost:5000/me

###
//logout
DELETE  http://localhost:5000/logout

### get all sample
GET http://localhost:5000/samples

### create sample
POST http://localhost:5000/samples
Content-Type: application/json

{
  "namaUnitPemohon": "Unit C",
  "tanggalSurat": "2025-04-08",
  "namaBahan": "Clay",
  "nomorPO": "PO12345",
  "nomorSurat": "Sufvbjsngvfs",
  "status": "pending"
}
### get id sample
GET http://localhost:5000/samples/ae00264d-2acf-4aa0-bb80-e98a2a9700e3

### update sample
PATCH http://localhost:5000/samples/ae00264d-2acf-4aa0-bb80-e98a2a9700e3
Content-Type: application/json

{
  "namaUnitPemohon": "Unit A",
  "tanggalSurat": "2025-04-08",
  "namaBahan": "sdds X",
  "nomorPO": "13271hjnjknkcwq",
  "nomorSurat": "hwsfffffbsbb",
  "status": "pending"
}
###
// delete Sample 
DELETE http://localhost:5000/samples/ae00264d-2acf-4aa0-bb80-e98a2a9700e3

###
//cek API get sample count 
GET http://localhost:5000/samples/count